### PR TITLE
added coverage yml

### PR DESCRIPTION
**Pull request by prsabahrami**

### CODE REVIEW

**Comment by prsabahrami** [comment]
@wolfv IINW, you need to add Codecov token's to this to work. Tokenless works only on PRs submitted from forks. 
Would you mind taking care of it?

**Comment by wolfv** [comment]
Will do!

**Comment by wolfv** [comment]
I added the token! :)

**Comment by prsabahrami** [comment]
> I added the token! :)

Great Thank you!

**Pull request merged**
