### PR TITLE
feat: implement `uname` and `which` as builtin functions

### PR DESCRIPTION
**Pull request by wolfv**
Seems to work quite well. Let me know what you think @certik / @prsabahrami :)

### CODE REVIEW

**Comment by certik** [comment]
I think we should remove the codecov/patch, since it always fails. I like the CI to be green. :)

**Review by certik — APPROVED** [review]
I tested on Windows, both which and uname works:
```
~/repos/shell(uname-which)$ which git
C:\Program Files\Git\cmd\git.exe
~/repos/shell(uname-which)$ uname -a
Windows_NT LAPTOP-XYE11GAT 10.0 22631 x86_64 MS/Windows (Windows 11)
```

**Comment by wolfv** [comment]
Should we merge then?! :)

**Comment by certik** [comment]
Go for it!

**Comment by wolfv** [comment]
I think I should remove a few `unwrap`'s to make things nice.

**Comment by prsabahrami** [comment]
I think it's great. Though, as you mentioned, I think it's better to replace the unwraps with proper error handling. =)

**Comment by prsabahrami** [comment]
Also, @wolfv  do you think you could add some tests? It would be great to start implementing tests for the newer features so they won't get stacked up altogether.

**Comment by wolfv** [comment]
Already in thanks to @prsabahrami in #135

**Pull request closed without merging**
