### PR TITLE
Source ~/.shellrc automatically if it exists

### LINKED ISSUE #95: Implement ~/.shellrc
So that I can add my own configuration there as a workaround to have "pixi" and "conda" installed.

### PR DESCRIPTION
**Pull request by certik**
Fixes #95.

### CODE REVIEW

**Review by prsabahrami — APPROVED** [review]
Awesome! 
Looks good to me.

**Comment by prsabahrami** [comment]
Do you think this should only be done as an option in interactive mode? I'm not sure how useful it would be but we can also add something like
```sh
cargo r ./scripts/script.sh --withrc
```

**Comment by certik** [comment]
Thanks for the review! I had to add an option `--norc` to skip sourcing it if requested (just like Bash allows), as I quickly found out that sourcing every time breaks my MSVC loading script, as my `~/.shellrc` sets the $PATH variable by overriding it (until #90 is fixed), so I need to skip sourcing it.

**Comment by certik** [comment]
It currently is an option in interactive mode only I think:
```
        execute(&script_text, &mut state).await?;
        if options.interact {                                                               interactive(Some(state), options.norc).await?;
        }
```
The script gets executed without sourcing `.shellrc`, and then if interactive mode is started, it will source it.

I think this takes care of most of the use cases, and we can since bash doesn't even have `--withrc`, we probably don't need it, but if we do, we can.

**Pull request merged**
