### PR TITLE
fix Correct if syntax

### LINKED ISSUE #166: Use the correct syntax for `if`
See https://github.com/prefix-dev/shell/pull/165.

### PR DESCRIPTION
**Pull request by prsabahrami**
Closes #166

### CODE REVIEW

**Comment by certik** [comment]
Let's test all of the combinations:
```bash
FOO=2
if [[ $FOO -eq 1 ]]; then
    echo "FOO is 1";
elif [[ $FOO -eq 2 ]]; then
    echo "FOO is 2";
else
    echo "FOO is not 1 or 2";
fi
```
and
```bash
FOO=2
if [[ $FOO -eq 1 ]]; then
    echo "FOO is 1"
elif [[ $FOO -eq 2 ]]; then
    echo "FOO is 2"
else
    echo "FOO is not 1 or 2"
fi
```
and
```bash
FOO=2
if [[ $FOO -eq 1 ]];
then
    echo "FOO is 1";
elif [[ $FOO -eq 2 ]];
then
    echo "FOO is 2";
else
    echo "FOO is not 1 or 2";
fi
```
and
```bash
FOO=2
if [[ $FOO -eq 1 ]]
then
    echo "FOO is 1";
elif [[ $FOO -eq 2 ]]
then
    echo "FOO is 2";
else
    echo "FOO is not 1 or 2";
fi
```

**Comment by prsabahrami** [comment]
I'll add these to the `tests` crate for now. But in the future, we should add a way to properly test the scripts in the script folder as well.

**Review by certik — APPROVED** [review]
Awesome, I think this looks great now!

**Comment by prsabahrami** [comment]
Agreed. 
I'll go ahead and merge this then.

**Pull request merged**
