### PR TITLE
feat: implement `--no-exit`

### PR DESCRIPTION
**Pull request by wolfv**
This is what powershell implements and it's quite useful in my opinion. 
It allows us to execute a script (after RC files) and then drop into an interactive prompt. For something like `pixi shell` this is very useful.

### CODE REVIEW

**Comment by wolfv** [comment]
@certik would be happy to hear your thoughts. For now, this can work as a custom "RC" file thing (e.g. you could point your shell to `shell init-file.sh --no-exit` and then have some aliases etc. defined,.

**Review by certik — APPROVED** [review]
I think that's fine. Isn't there a more descriptive command line option? I first thought `--no-exit` will not allow you to exit, which might not be what was intended. :)

**Comment by wolfv** [comment]
@certik what do you think about `--continue`?

**Comment by certik** [comment]
That's better. Maybe also `--interact` ? I think the main difference is that `shell a.sh` executes it and returns. While `shell a.sh --interact` (or `shell a.sh --continue`) will open an interactive prompt.

**Comment by prsabahrami** [comment]
@wolfv @certik Are you okay with merging this? I think this can be quite useful.

**Review by prsabahrami — APPROVED** [review]
Used `--interact` instead of `--no-exit`.

**Comment by wolfv** [comment]
Works for me!

**Pull request merged**
